version: '2'
services:
    nats:
        image: nats
        container_name: nats-main
        ports:
            - '4222:4222'
            - '6222:6222'
            - '8222:8222'
        command: ['-js', '-m', '8222']
