version: '2'

networks:
  app-tier:
    driver: bridge

services:
  nats:
    image: 'bitnami/nats:latest'
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    networks:
      - app-tier
    environment:
      - NATS_ENABLE_AUTH=yes
      - NATS_PASSWORD=123456789
